<?php
function svendborg_admin_theme_custom_preprocess_html(&$variables) {
  // Add conditional stylesheets for node/term edit pages on admin theme.
  if ((arg(0) == 'node' && (arg(2) == 'edit' || arg(1) == 'add')) || (arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2)) && arg(3) == 'edit') || arg(0) == 'admin') {
    drupal_add_css(drupal_get_path('module', 'svendborg_admin_theme_custom') . '/admin_theme_custom.css');
  }
}

/**
 * Implements hook_library_alter().
 */
function svendborg_admin_theme_custom_library_alter(&$libraries, $module) {
  if ($module == 'media') {
    $path = drupal_get_path('module', 'svendborg_admin_theme_custom');
    $libraries['media_browser_page']['css'][$path . '/admin_theme_custom.css']['group'] = CSS_DEFAULT;
  }
}

